# 公共配置文件
spring:
  application:
    name: duckoj-backend-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1::8848  # 注册到 nacos 服务
    gateway:
      routes:
        - id: duckoj-backend-user-service
          uri: lb://duckoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: duckoj-backend-question-service
          uri: lb://duckoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: duckoj-backend-judge-question-service
          uri: lb://duckoj-backend-judge-question-service
          predicates:
            - Path=/api/judge/**
  main:
    web-application-type: reactive

server:
  port: 8104

knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2

